name: CI

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    uses: metacraft-labs/nixos-modules/.github/workflows/reusable-flake-checks-ci-matrix.yml@main
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    with:
      runner: '["self-hosted", "nixos", "x86-64-v2"]'
