name: CI

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    uses: metacraft-labs/nixos-modules/.github/workflows/ci.yml@main
    secrets: inherit
